name: Labs CI

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Show Python version
        run: python --version

      - name: List repository files
        run: ls

      - name: Confirm workflow
        run: echo "GitHub Actions is running"
